### ISSUE TITLE
[CHANGE] Melhorar telas de recuperação de senha

### ISSUE THREAD

**Issue by 710lucas** [universi-me/universi-front#158]
# -- Mudanças--
Pensar em textos e um design que deixe as páginas melhores

## Motivação
Telas muito básicas com poucas instruções

- [ ] Adicionar segunda caixa para repetir a senha

**Comment by julio-ufpb** [comment]
se possível por outra caixinha para repetir a senha, para evitar de digitar a senha errada sem querer

**Comment by NiiMiyo** [comment]
Resolvido por #574
