### ISSUE TITLE
[FEAT] Adicionar autenticação ao editar perfil

### ISSUE THREAD

**Issue by 710lucas** [universi-me/universi-front#263]
# -- Feature --
Pedir senha do usuário e verificar sessão ao editar perfil 

## Descrição
Criação de componente para que possa ser implementado em outras telas

**Comment by julio-ufpb** [comment]
lucas, quando adicionei a verificação por senha ao editar profile na api, acabei ajustando tbm no front #278

**Comment by 710lucas** [comment]
beleza, valeu júlio 👍
Resolvida em #278
