### ISSUE TITLE
[CHANGE]Atualizar Header

### ISSUE THREAD

**Issue by mathzsl** [universi-me/universi-front#34]
# -- Mudanças--

## Descrição
1. Alterar esquema de cores
    * Cor de fundo #F2C02A
    * Cor dos textos: #1D1D1D
1. Usar a logo do universi.me
1. Diminuir altura da barra de busca

**Comment by camilatereza** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Melhoria] Adequação dos módulos criados ao novo front-end](https://trello.com/c/zEGcnyTO/16-melhoria-adequa%C3%A7%C3%A3o-dos-m%C3%B3dulos-criados-ao-novo-front-end)
