### ISSUE TITLE
[CHANGE] Header quando logado

### ISSUE THREAD

**Issue by NiiMiyo** [universi-me/universi-front#35]
# -- Mudanças--

## Descrição
* Alterar o botão "Entrar" para "Sair" na header quando o usuário estiver logado
* Adicionar foto de usuário ao lado do botão "Sair".
    * Clicar na foto leva o usuário para o próprio perfil

**Comment by camilatereza** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Autenticação] login e logout dos usuários](https://trello.com/c/h7o7tsOl/10-autentica%C3%A7%C3%A3o-login-e-logout-dos-usu%C3%A1rios)
