### ISSUE TITLE
[FEAT] Grupo: Excluir

### ISSUE THREAD

**Issue by 710lucas** [universi-me/universi-front#384]
## Descrição

O dono ou dona do grupo deve ser capaz de excluí-lo.

(1) Acrescentar opção de excluir grupo no menu de contexto

![Image](https://github.com/universi-me/universi-front/assets/288272/a5c0fd5d-f8be-48c7-9790-5f726f5b8e21)

Exibir mensagem confirmando a exclusão do grupo.

Excluir grupo logicamente, no banco.

**Comment by NiiMiyo** [comment]
> Acrescentar opção de excluir grupo no menu de contexto

Acho que seria melhor colocar o botão na listagem de opções de subgrupos porque já evita de ter que fazer alguma condição pro botão aparecer/desaparecer na organização. Mais simples a implementação e mais difícil de rolar algum bug.

![image](https://github.com/universi-me/universi-front/assets/62383247/f163a49f-cea3-4028-bfef-128526d3601e)

**Comment by 710lucas** [comment]
eu acho interessante, mas ai não daria pra editar o grupo da organização, já que ele nunca aparece nessa listagem

**Comment by NiiMiyo** [comment]
O de editar pode ser ali msm, o de excluir que tô falando pra ficar na listagem

Ou ainda dá pra manter o botão nos dois e colocar condição pra organização, aí quem tiver usando não se perde

**Comment by 710lucas** [comment]
aaah, entendi, acho boa essas ideias, acho que a de mover o botão de deletar pro menu de baixo (o da listagem) é melhor
