### ISSUE TITLE
[CHANGE] Usar a API correta

### ISSUE THREAD

**Issue by NiiMiyo** [universi-me/universi-front#40]
# -- Mudanças--

## Descrição
No momento a conexão com a API é **apenas local** ([UniversimeApi.ts](https://github.com/universi-me/universi-front/blob/8a8386d6088cd80da9f116d31e9b4aed17e38dc2/src/hooks/UniversimeApi.ts#L4-L5)).

Precisa ser feita a configuração para conectar com a API online quando em produção e com a API local quando em teste

**Comment by whoisclebs** [comment]
@NiiMiyo o ideal é isso ser feito por variavel de ambiente já que teremos diversos ambientes.

**Comment by julio-ufpb** [comment]
![image](https://github.com/universi-me/universi-front/assets/55258516/60b13a90-cef7-49a8-9067-2da6b9925cab)
https://pt.vitejs.dev/guide/env-and-mode.html
