### ISSUE TITLE
Não listar usuário "admin" entre os usuários

### ISSUE THREAD

**Issue by rodrigor** [universi-me/universi-front#429]

**Comment by rodrigor** [comment]
O usuário admin é um usuário de sistema. Não deve ser listado entre os usuários cadastrados.



![Image](https://github.com/universi-me/universi-front/assets/288272/7da96d9e-2c21-4cec-8626-7f7e84f23ed9)

**Comment by NiiMiyo** [comment]
Concluído em https://github.com/universi-me/universi-api/pull/730
