### ISSUE TITLE
[BUG] Autenticação do Universi.me com Google, usando email do DCX

### ISSUE THREAD

**Issue by rodrigor** [universi-me/universi-front#476]
Um teste:

Fazer login usando autenticação do Google, com email do DCX, de um usuário inexistente no Universi.me.
Ao se autenticar, o usuário deve ser levado para a tela de configuração do perfil.

**Comment by NiiMiyo** [comment]
Ao acessar o Universi.me usando login com Google o sistema entra em loop infinito enviando requests de login à API.
