### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by 710lucas** [universi-me/universi-front#63]
# -- Bug Report 🐛 --

## Comportamento esperado
Ao se logar o usuario deveria ir para a pagina do seu perfil

## Comportamento atual
O usuário é redirecionado para a pagina /profile/undefined

Eu dei uma olhada com o debuger do firefox, e aparentemente ao se logar, a unica credencial que é setada corretamente é o token, nem o usuario nem o profile persistem apos o metodo signin ser executado.
Eu observei também que eles se perdiam quando eram passados para o metodo setLoggedUser, eu mudei os nomes dos atributos do metodo para user2 e profile2, o que fez com que os dados se persistissem no metodo, mas ao dar o return e voltar para a parte onde deveria ser redirecionado os dados parecem que se perdem novamente.

Essa é a minha primeira vez olhando esse código, então eu não sei se eu não observei direito alguma função que eu deveria ter visto ou não, mas foi isso que eu encontrei olhando o código a partir do momento que o botão de realizar login é apertado

## Passos para reproduzir

1. Se logar como admin

## Browser, dispositivo e sistema operacional
Browser: Firefox

**Comment by julio-ufpb** [comment]
para persistir dados entre as páginas acho q seria salvar/obter em LocalStorage

**Comment by 710lucas** [comment]
#64 Possível correção do bug
